version: 2.1

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: go fmt
          command: make fmt
      - run:
          name: go vet
          command: make vet
      - run:
          name: go lint
          command: make lint
      - run:
          name: go test
          command: make test

orbs:
  go: circleci/go@1.1.1

workflows:
  main:
    jobs:
      - build
